### ISSUE TITLE
Request: add space for trackpoint module

### ISSUE THREAD

**Issue by btittelbach** [sevmeyer/chrumm-keyboard#10]
Hi,

## Feature Request
I would be awesome if you could add an optional feature for the body stl generator, so people can more easily duplicate my modification of Chrumm in which I  added a trackpoint module in the middle.

Earlier you said you wanted Chrumm to be a portifolio project and prefer to write your own code, so I though it would be better to open an issue rather than modify the nice STL generator code and then have an unaccepted pull-request.

## Rationale
I found that the space in the middle of chrumm, lends itself perfectly to add a trackpoint module. Even more so, if the split is increased to something more ergonomic. (I used 20° split, which may even be a bit too much, but comes close to my ideal)

Having a mouse pointer integrated with the keyboard, reduces the need to move the hands away from the keyboard position. 

The FN-Layer can be used for mouse buttons.
If someone is interested in my QMK configuration that drives the trackpoint, it can be found [here](https://github.com/btittelbach/chrumm-qmk/tree/main/chrumm/keymaps/btittelbach_65keys_mouse) 

## Specs

The Trackpoint Module has the following dimensions:
width: 28,7mm
length: 31,2mm
height: 0,7mm höhe

Ideally the the generator would add a small indentation for the module as well as a hole for the cable and a wedge to get the cables to the hole as well as a small circular pit below the trackpoint nub to accomodate the rivets.

Below the trackpoint nub, a circular indentation with additional height of 0,5mm and diameter of 14mm would be needed to accommodate the rivets seen on the photo. Unfortunately I forgot to add those to my design. The circle center should be 1,3mm from the edge in width-axis and 0,6mm from the edge in length-axis. (the smaller edge-center distances were measured.

The pin-header of the trackpoint module is 14,5mm in width and centered with 7,5mm distance from the edge on both sides on the width-axis. Though the 3 pins on the left side are for mouse buttons and are not needed. Pin-pitch is about 1,72mm.

![chrumm_trackpoint_space_freecad_screenshot](https://github.com/sevmeyer/chrumm-keyboard/assets/635660/e8d10c53-b99d-4727-a977-b7de2806ce29)
 
![chrum_mounted_trackpoint](https://github.com/sevmeyer/chrumm-keyboard/assets/635660/ff928448-0a53-4591-8c54-74941993f0f4)

**Comment by sevmeyer** [comment]
It is really neat that you are making use of Chrumm and come up with new ideas.

However, after years of development and refinement, my work on Chrumm is done.
I do not intend to add new features, especially if I have not physically tested them myself.

I apologize for not communicating this more clearly in the repository.

Of course, you are welcome to maintain your own fork, as many people have done with the Dactyl for example.
