### ISSUE TITLE
Chrumm 36

### ISSUE THREAD

**Issue by sahidrahman404** [sevmeyer/chrumm-keyboard#2]
Are there any plans to create a variant of this keyboard with 36 keys?

**Comment by sevmeyer** [comment]
I assume you refer to Miryoku. There are no plans to support such small layouts, sorry.

The current construction of the body and PCB assumes at least two pinky columns.
Also, the Pico would not easily fit in its current orientation.
Ultimately, Miryoku would require non-trivial adjustments.
