### ISSUE TITLE
stls

### ISSUE THREAD

**Issue by TuneClausen** [sevmeyer/chrumm-keyboard#3]
Hello. I'm in love with the chrumm and have today recieved the pcbs. Could you upload the stls that you have used for your layout? I fear that I'm too stupid to use the python files that you have supplied :)

**Comment by giovanniborella** [comment]
Check the releases: https://github.com/sevmeyer/chrumm-keyboard/releases/tag/1.0

**Comment by sevmeyer** [comment]
Thanks @giovanniborella.

On the releases page you can also download the 3mf files,
which contain the print settings for [PrusaSlicer] 2.6.

[PrusaSlicer]: https://www.prusa3d.com/page/prusaslicer_424/
